# Generated by Django 5.1.15 on 2026-10-07 16:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=core.models.default_expires_at, null=True),
        ),
    ]
