# Generated by Django 5.1.15 on 2026-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_link_expires_at_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
